### ISSUE TITLE
Project status [stopped]

### ISSUE THREAD

**Issue by KODerFunk** [pyromaniac/hoof#12]
I try all actions, step by step, by instructions, but has project [stopped](on).
May be problem around unicorn execution.
What i can try?

**Comment by vrinek** [comment]
+1

**Comment by ku1ik** [comment]
Yeah, what's the status of this project?

**Comment by vrinek** [comment]
I think it's dead

**Comment by dtriley4** [comment]
I'm also having this problem with ubuntu 11.04 any clues?

**Comment by KODerFunk** [comment]
It is impossible to wait. 
Now I watch actively developing project, but in private repo. Some time later it will open.

**Comment by arturtr** [comment]
Same problem

**Comment by itschn** [comment]
+1

**Comment by KODerFunk** [comment]
Close beacase not maintained
