### ISSUE TITLE
Гггг

### ISSUE THREAD

**Issue by myserg** [pyromaniac/hoof#3]
Интересно, вы в курсе, что телодвижения типа "create symlink in ~/.pow" эквивалентны добавлению домена в /etc/hosts? И ничего изобретать не нужно.

**Comment by pyromaniac** [comment]
Да, я в курсе, спасибо.

А можно добавить в hosts *.myhost.dev?

**Comment by myserg** [comment]
Это такой способ убить время? just wondering

**Comment by pyromaniac** [comment]
Нет, это способ решить интересную проблему и получить очередную пачку знаний.

**Comment by myserg** [comment]
Если нужно добавить все поддомены - вам ответили в ror2ru как (настроить локальный dns-сервер). Вы возразили, что это "неправильно", поэтому я и написал про hosts. Один bash alias и не надо ничего компилировать.

**Comment by pyromaniac** [comment]
Я прекрасно знаю, как настроить локальный днс сервер.
Тут такое дело: я ебанулся на отличненько и решил сделать. И сделал. Did it for lulz, ok?
Кто-то увидит в этом смысл, а кто-то и без этого умный

**Comment by myserg** [comment]
:) А, ок
