### ISSUE TITLE
POST запросы

### ISSUE THREAD

**Issue by olancheg** [pyromaniac/hoof#5]
с POST запросами какая то беда

Chrome ругается:
Ошибка 324 (net::ERR_EMPTY_RESPONSE): Сервер разорвал соединение, не отправив данные.

development.log:
Started POST "/search" for 127.0.0.1 at 2011-05-17 23:53:18 +0400
и тишина...

Gemfile - https://gist.github.com/977260

**Comment by pyromaniac** [comment]
В файрфоксе работает нормально. То ли хром отправляет данные вторым запросом, то ли EM их так криво принимает.

DATA
"POST /admin/session/create HTTP/1.1\r\nHost: blessus.dev\r\nConnection: keep-alive\r\nReferer: http://blessus.dev/admin/session/new\r\nContent-Length: 177\r\nCache-Control: max-age=0\r\nOrigin: http://blessus.dev\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.24 (KHTML, like Gecko) Ubuntu/11.04 Chromium/11.0.696.65 Chrome/11.0.696.65 Safari/534.24\r\nContent-Type: application/x-www-form-urlencoded\r\nAccept: application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,_/_;q=0.5\r\nAccept-Encoding: gzip,deflate,sdch\r\nAccept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4\r\nAccept-Charset: windows-1251,utf-8;q=0.7,*;q=0.3\r\nCookie: _session_id=3003a9e57ae6c7a19e803b2d39512211\r\n\r\n"
Serve blessus.dev/admin/session/create
DATA
"utf8=%E2%9C%93&authenticity_token=6sAXqFghcR37MAolIwvLg%2FUW%2BUO4ljbmhTpLzjdyWGQ%3D&typus_user%5Bemail%5D=kinwizard%40gmail.com&typus_user%5Bpassword%5D=icdreams&commit=Sign+in"

Вот из этого лога видно, что post-данные пришли уже вторым запросом. Думаю, это таки EM что-то не так отрабатывает. Надо будет Полностью дебажить, а дело не быстрое. Так что пока ff )

**Comment by pyromaniac** [comment]
Всё, фиксед. Радуемся, тестим.
